tests
testNavigation

	self
		assert: BootstrapCssStyles breadcrumb equals: 'breadcrumb';
		assert: BootstrapCssStyles nav equals: 'nav';
		assert: BootstrapCssStyles navJustified equals: 'nav-justified';
		assert: BootstrapCssStyles navPills equals: 'nav-pills';
		assert: BootstrapCssStyles navStacked equals: 'nav-stacked';
		assert: BootstrapCssStyles navTabs equals: 'nav-tabs';
		assert: BootstrapCssStyles navbar equals: 'navbar';
		assert: BootstrapCssStyles navbarBrand equals: 'navbar-brand';
		assert: BootstrapCssStyles navbarButton equals: 'navbar-btn';
		assert: BootstrapCssStyles navbarCollapse equals: 'navbar-collapse';
		assert: BootstrapCssStyles navbarDefault equals: 'navbar-default';
		assert: BootstrapCssStyles navbarFixedBottom equals: 'navbar-fixed-bottom';
		assert: BootstrapCssStyles navbarFixedTop equals: 'navbar-fixed-top';
		assert: BootstrapCssStyles navbarForm equals: 'navbar-form';
		assert: BootstrapCssStyles navbarHeader equals: 'navbar-header';
		assert: BootstrapCssStyles navbarInverse equals: 'navbar-inverse';
		assert: BootstrapCssStyles navbarLeft equals: 'navbar-left';
		assert: BootstrapCssStyles navbarRight equals: 'navbar-right';
		assert: BootstrapCssStyles navbarLink equals: 'navbar-link';
		assert: BootstrapCssStyles navbarStaticTop equals: 'navbar-static-top';
		assert: BootstrapCssStyles navbarText equals: 'navbar-text'