tests
testDropdowns

	self
		assert: BootstrapCssStyles divider equals: 'divider';
		assert: BootstrapCssStyles dropdown equals: 'dropdown';
		assert: BootstrapCssStyles dropdownHeader equals: 'dropdown-header';
		assert: BootstrapCssStyles dropdownMenu equals: 'dropdown-menu';
		assert: BootstrapCssStyles dropdownMenuLeft equals: 'dropdown-menu-left';
		assert: BootstrapCssStyles dropdownMenuRight equals: 'dropdown-menu-right';
		assert: BootstrapCssStyles dropdownToggle equals: 'dropdown-toggle';
		assert: BootstrapCssStyles dropup equals: 'dropup'