tests
testHelperClasses

	self
		assert: BootstrapCssStyles backgroundDanger equals: 'bg-danger';
		assert: BootstrapCssStyles backgroundInfo equals: 'bg-info';
		assert: BootstrapCssStyles backgroundPrimary equals: 'bg-primary';
		assert: BootstrapCssStyles backgroundSuccess equals: 'bg-success';
		assert: BootstrapCssStyles backgroundWarning equals: 'bg-warning'.

	self
		assert: BootstrapCssStyles caret equals: 'caret';
		assert: BootstrapCssStyles centerBlock equals: 'center-block';
		assert: BootstrapCssStyles clearfix equals: 'clearfix';
		assert: BootstrapCssStyles close equals: 'close';
		assert: BootstrapCssStyles hidden equals: 'hidden';
		assert: BootstrapCssStyles invisible equals: 'invisible';
		assert: BootstrapCssStyles pullLeft equals: 'pull-left';
		assert: BootstrapCssStyles pullRight equals: 'pull-right';
		assert: BootstrapCssStyles show equals: 'show'.

	self
		assert: BootstrapCssStyles screenReaderOnly equals: 'sr-only';
		assert: BootstrapCssStyles screenReaderOnlyFocusable equals: 'sr-only-focusable'.

	self
		assert: BootstrapCssStyles textDanger equals: 'text-danger';
		assert: BootstrapCssStyles textHide equals: 'text-hide';
		assert: BootstrapCssStyles textInfo equals: 'text-info';
		assert: BootstrapCssStyles textMuted equals: 'text-muted';
		assert: BootstrapCssStyles textPrimary equals: 'text-primary';
		assert: BootstrapCssStyles textSuccess equals: 'text-success';
		assert: BootstrapCssStyles textWarning equals: 'text-warning'