SystemOrganization addCategory: #Willow!
SystemOrganization addCategory: 'Willow-Applications'!
SystemOrganization addCategory: 'Willow-Deprecated'!
SystemOrganization addCategory: 'Willow-Frontend'!
SystemOrganization addCategory: 'Willow-Javascript'!
SystemOrganization addCategory: 'Willow-Libraries'!
SystemOrganization addCategory: 'Willow-WebInteraction'!
SystemOrganization addCategory: 'Willow-WebViews'!
