"
All the Willow specific Css classes
"
Class {
	#name : #WillowCssStyles,
	#superclass : #Object,
	#category : #'Willow-WebViews'
}

{ #category : #'accessing - general' }
WillowCssStyles class >> dialogContainer [

	^'willow-dialog-container'
]

{ #category : #'accessing - general' }
WillowCssStyles class >> disabledComponent [

	^'willow-disabled-component'
]

{ #category : #'accessing - general' }
WillowCssStyles class >> fadingNotification [

	^'willow-fading-notification'
]

{ #category : #'accessing - general' }
WillowCssStyles class >> loading [

	^'willow-loading'
]

{ #category : #'accessing - general' }
WillowCssStyles class >> willow [

	^'willow'
]
