tests
testRoles

	self
		assert: BootstrapConstants alert equals: 'alert';
		assert: BootstrapConstants button equals: 'button';
		assert: BootstrapConstants group equals: 'group';
		assert: BootstrapConstants navigation equals: 'navigation';
		assert: BootstrapConstants presentation equals: 'presentation';
		assert: BootstrapConstants progressbar equals: 'progressbar';
		assert: BootstrapConstants separator equals: 'separator';
		assert: BootstrapConstants tablist equals: 'tablist';
		assert: BootstrapConstants toolbar equals: 'toolbar'